pandocs --template=template.html --metadata pagetitle="links.html" links.md -o links.html
pandoc --template=template.html --metadata pagetitle="mailinglist.html" mailinglist.md -o mailinglist.html
pandoc --template=template.html --metadata pagetitle="daihyo_yakuin.html" daihyo_yakuin.md -o daihyo_yakuin.html
pandoc --template=template.html --metadata pagetitle="keyword.html" keyword.md -o keyword.html
pandoc --template=template.html --metadata pagetitle="keyword-e.html" keyword-e.md -o keyword-e.html
pandoc --template=template.html --metadata pagetitle="topical_sesion.html" topical_session.md -o topical_session.html
pandoc --template=template.html --metadata pagetitle="meetinginfo.html" meetinginfo.md -o meetinginfo.html
pandoc --template=template.html --metadata pagetitle="index.html" main.md -o index.html
pandoc --template=template.html --metadata pagetitle="symposium.html" symposium.md -o symposium.html
pandoc --template=template.html --metadata pagetitle="r2meeting.html" r2meeting.md -o r2meeting.html
pandoc --template=template.html --metadata pagetitle="boardmeeting.html" boardmeeting.md -o boardmeeting.html
pandoc --template=template.html --metadata pagetitle="collaboration.html" collaboration.md -o collaboration.html
pandoc --template=template.html --metadata pagetitle="invite.html" invite.md -o invite.html
pandoc --template=template.html --metadata pagetitle="RonbunWakate.html" RonbunWakate.md -o RonbunWakate.html
